type: chart
rootfs:
  - image: samsung_cnct/technical-on-boarding-container
    buildArgs: 
      - arg: BUILD
        env: GIT_COMMIT
    context: technical-on-boarding-container
    dockerContext: .
    chart: technical-on-boarding
    value: image
configs:
  - chart: technical-on-boarding
    timeout: 600
    retries: 1
    release: onboarding
    test: 
      values:
        - key: ingress
          value: "false"
    stage: 
      values:
        - key: ingress
          value: "true"
        - key: onboard.org
          secret: jobs/onboarding/github-org/stage
        - key: onboard.repo
          secret: jobs/onboarding/github-repo/stage
        - key: onboard.clientId
          secret: jobs/onboarding/github-app-client-id/stage
        - key: onboard.clientSecret
          secret: jobs/onboarding/github-app-client-secret/stage
    prod:
      values:
        - key: ingress
          value: "false"  
        - key: onboard.org
          secret: jobs/onboarding/github-org/prod
        - key: onboard.repo
          secret: jobs/onboarding/github-repo/prod
        - key: onboard.clientId
          secret: jobs/onboarding/github-app-client-id/prod
        - key: onboard.clientSecret
          secret: jobs/onboarding/github-app-client-secret/prod

stage:
  deploy: true
prod: 
  doDeploy: versionfile

 
