kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 }} 
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  ONBOARD_ORG: {{.Values.onboard.org}}
  ONBOARD_REPO: {{.Values.onboard.repo}}
  {{- if ne .Values.onboard.clientEndpoint ""}}
  ONBOARD_CLIENT_ENDPOINT: {{.Values.onboard.clientEndpoint}}
  {{- else }}
  ONBOARD_CLIENT_ENDPOINT: ""  # Blank => default https://api.github.com
  {{- end}}
